const CRIMECATEGORIES = [
  { id: "18", value: "Abuse of Women or Children" },
  { id: "33", value: "Appreciation" },
  { id: "19", value: "Archeological Issue" },
  { id: "20", value: "Assault" },
  { id: "8", value: "Bribery and Corruption" },
  { id: "15", value: "Complaint against Police" },
  { id: "6", value: "Criminal Offence" },
  { id: "11", value: "Cybercrime" },
  { id: "28", value: "Demonstration / Protest / Strike" },
  { id: "7", value: "Environmental Issue" },
  { id: "36", value: "Exchange Fault" },
  { id: "21", value: "Foreign Employment Issue" },
  { id: "14", value: "Frauds / Cheating" },
  { id: "22", value: "House Breaking" },
  { id: "37", value: "Illegal Mining" },
  { id: "38", value: "Industrial / Labour Dispute" },
  { id: "43", value: "Information" },
  { id: "2", value: "Intellectual Property Dispute" },
  { id: "23", value: "Miscellaneous" },
  { id: "39", value: "Mischief / Sabotage" },
  { id: "24", value: "Murder" },
  { id: "13", value: "Narcotics / Dangerous Drugs" },
  { id: "9", value: "National Security" },
  { id: "25", value: "Natural Disaster" },
  { id: "34", value: "Offence / Act against Public Health" },
  { id: "35", value: "Offence against Public Property" },
  { id: "26", value: "Organized Crime" },
  { id: "17", value: "Personal Complaint" },
  { id: "12", value: "Police Clearance" },
  { id: "27", value: "Property Disputes" },
  { id: "3", value: "Robbery" },
  { id: "29", value: "Sexual Offences" },
  { id: "44", value: "Suggestion" },
  { id: "5", value: "Terrorism Related" },
  { id: "40", value: "Theft" },
  { id: "30", value: "Threat & Intimidation" },
  { id: "31", value: "Tourist Harassment" },
  { id: "10", value: "Traffic & Road Safety" },
  { id: "41", value: "Treasure Hunting" },
  { id: "16", value: "Vice Related" },
  { id: "32", value: "Violation of Immigration Laws" },
];

const DEPARTMENT = [
  { key: "1", value: "Colombo Police Station" },
  { key: "2", value: "Mount Lavinia Police Station" },
  { key: "3", value: "Gampaha Police Station" },
  { key: "4", value: "Negombo Police Station" },
  { key: "5", value: "Kandy Police Station" },
  { key: "6", value: "Peradeniya Police Station" },
  { key: "7", value: "Galle Police Station" },
  { key: "8", value: "Colombo Grama Niladari Division" },
  { key: "9", value: "Mount Lavinia Grama Niladari Division" },
  { key: "10", value: "Gampaha Grama Niladari Division" },
  { key: "11", value: "Negombo Grama Niladari Division" },
  { key: "12", value: "Kandy Grama Niladari Division" },
  { key: "13", value: "Peradeniya Grama Niladari Division" },
  { key: "14", value: "Galle Grama Niladari Division" },
];

const CRIME_LABELS = [
  "Crime Type",
  "Incident Details",
  "Select department",
  "Preview",
]; // Define your step labels
export { CRIMECATEGORIES, DEPARTMENT, CRIME_LABELS };
